### ISSUE TITLE
CommonJS / Publish on npm

### ISSUE THREAD

**Issue by bpierre** [therealglazou/jscssp#1]
It would be great to have jscssp on [npm](https://www.npmjs.org/).

What would you think of using CommonJS to manage the dependencies?

If you don’t want to, it’s still possible to wrap everything in a big function, and add a `module.exports = CSSParser`.

**Comment by therealglazou** [comment]
Honestly, I don't want to do that. I want JSCSSP to remain plain vanilla JS and independent from all external dependencies. Wrapping up everything into a big function is trivial enough for people to have it done by a Makefile or any automated mechanism. Sorry, no.

**Comment by bpierre** [comment]
Just to be sure, sorry if you already know that: the wrapper solution won’t impact the existing code. As you said, it’s just a new task in the Makefile to build a Node/Browserify version. Node.js is a huge JavaScript community, and I think jscssp could really benefit from being published on npm.

**Comment by therealglazou** [comment]
Ah, that's different is you see it as an optional Makefile thingy. Yes, that would be interesting then. Do you want to contribute some code there and I'll review it?

**Comment by bpierre** [comment]
Yes! I will open a pull request.
